# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: my@mail.com
author_name: John Doe
contract_name: limit_order
deployment_language: python
preset_name: starter
project_name: limit_order

