# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.8
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: my@mail.com
author_name: John Doe
preset_name: starter
project_name: limit_order-frontend

